[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "eessi_tests"
version = "0.0.1"

[tool.setuptools]
#packages = ["eessi_checks", "eessi_utils", "eessi_checks.applications"]
package-dir = {"" = "eessi/reframe"}

[tool.setuptools.packages.find]
where = ["eessi/reframe"]
namespaces = false
