name: Static Analysis
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{format('{0}:{1}:{2}', github.repository, github.ref, github.workflow)}}
  cancel-in-progress: true

jobs:
  python-linting:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: install Python packages
      run: |
        pip install --upgrade pip
        pip install --upgrade flake8

    - name: Run flake8 to verify PEP8-compliance of Python code
      run: flake8
